apiVersion: v1
kind: Secret
metadata:
  name: users
  namespace: clickhouse
stringData:
  clickhouse.xml: |
    <yandex>
        <users>
          <clickhouse>
              <profile>default</profile>
                <networks>
                      <ip>::/0</ip>
                </networks>
              <password_sha256_hex>7e099f39b84ea79559b3e85ea046804e63725fd1f46b37f281276aae20f86dc3</password_sha256_hex>
              <quota>default</quota>
          </clickhouse>
        </users>
    </yandex>