apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - port: 8123
      name: http
    - port: 9000
      name: native